// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from "storyblok";
export interface AssetStoryblok {
  alt?: string;
  copyright?: string;
  id: number;
  filename: string;
  name: string;
  title?: string;
  focus?: string;
  [k: string]: any;
}

export interface EpisodeStoryblok {
  number: string;
  artist: string;
  id: string;
  image: AssetStoryblok;
  description: string;
  component: "episode";
  _uid: string;
  [k: string]: any;
}

export interface RichtextStoryblok {
  type: string;
  content?: RichtextStoryblok[];
  marks?: RichtextStoryblok[];
  attrs?: any;
  text?: string;
  [k: string]: any;
}

export interface PostStoryblok {
  image?: AssetStoryblok;
  body: RichtextStoryblok;
  component: "post";
  _uid: string;
  [k: string]: any;
}
